### ISSUE TITLE
suggestion: add YAML support for model

### ISSUE THREAD

**Issue by nodece** [casbin/casbin#432]
YAML is a human friendly data serialization standard for all programming languages.

It can help users to write and verify the model .

## How to help users to write and verify the model?

We need to write the `YAML schema` then IDE can provides hints based upon `YAML schema` provided to helps user write schema efficiently.

Please refer to https://dzone.com/articles/two-ways-configuration-documentation-with-springnb to write YAML schema then publish to https://github.com/SchemaStore/schemastore.

**Comment by hsluoyz** [comment]
We can add support for YAML but do not break current API.

**Comment by nodece** [comment]
Here want to collection some YAML config.

**Comment by nodece** [comment]
consider multiple `p`, `e` and `m`, You can refer to https://github.com/casbin/casbin-rs/pull/123

**Comment by GopherJ** [comment]
@hsluoyz @nodece I also think we should move to `YAML/TOML` because with ini we will have limited information, we don't know how to indicate for example `m1` should use `e2`.

Also we should maybe find a way to indicate which `p` will we use for which `m`

**Comment by GopherJ** [comment]
To summary:

1. we need to find a way to express: `m[a] should use e[b]` as merging effects strategy.
2. we need to find a way to express: `m[a] uses p[b]`, **one matcher can only have one kind of ptype**
3. we need to find a way to avoid: `p2, p3, p4, p5...., e1, e2, e3, e4` and make it possible to be customlized by users, because if users have two types of matchers, we often would like to make every matcher has a meaningful name instead of just `m1, m2, e1, e2, p1, p2`

**Comment by hsluoyz** [comment]
@GopherJ 

> we need to find a way to express: m[a] should use e[b] as effects merge strategy.
> we need to find a way to express: m[a] has used p[b], one matcher can only have one kind of ptype, otherwise panic

m2 maps to e2 and p2.
m["admin"] maps to e["admin"] and p["admin"]

> we need to find a way to avoid write: p2, p3, p4, p5...., e1, e2, e3, e4 and make it possible to be customlized by users, because if users have two types of matchers/effects/policies, they often would like to make every type of matcher/effect/policy has a meaningful name instead of just m1, m2, e1, e2, p1, p2

We will support both p, p2, p3... and p["basic"], p["admin"], ...

**Comment by GopherJ** [comment]
@hsluoyz 

> m2 maps to e2 and p2, m["admin"] maps to e["admin"] and p["admin"]

The latter is not supported yet, we also don't know which p are we using for `m`, if `p2` should only be used in `m2` it's better to panic when we load model instead of panic during enforce.

**Comment by nodece** [comment]
We provide a YAML config:

```yml
request_definition:
  - name: r
    token:
      - sub
      - obj
      - act

policy_definition:
  - name: p
    token:
      - sub_rule
      - obj
      - act

  - name: p2
    token:
      - sub_rule
      - obj
      - act

matchers:
  - name: m
    token: eval(p.sub_rule) && r.obj == p.obj && r.act == p.act
    effect: some(where (p.eft == allow))

  - name: m2
    token: m && m1 && eval(p2.sub_rule) && r.obj == p2.obj && r.act == p2.act
    with:
      - m # Use matcher name is m
      - m1 # Use matcher name is m1
    effect: some(where (p.eft == allow)) 
```

It looks very complicated, but we support autocomplete, so easy.
